version: '2.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    volumes:
      - ./:/home/node:delegated # "delegated" = the container’s view is authoritative (performance improvement)
    depends_on:
      - db
    ports:
      - '3000:3000'
      - '9229:9229'
  db:
    image: mongo:bionic
