version: '2.4'

services:
  web:
    build: .
    volumes:
      - ./:/home/node:delegated # "delegated" = the container’s view is authoritative (performance improvement)
    depends_on:
      - db
    ports:
      - '3000:3000'
  db:
    image: mongo:bionic
